import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider} from '@clerk/nextjs'
import "./globals.css";
import {Toaster} from 'react-hot-toast'
import {shadesOfPurple,dark } from "@clerk/themes";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
    appearance={{
      baseTheme:  [dark],
      variables: {
        colorPrimary: "white",
        colorText: "#ffffff"
      }
    }}
    >
      
    <html lang="en" suppressHydrationWarning={true}>
      <body className={inter.className}>

              <div className="flex items-start justify-center min-h-screen">
              <Toaster
  position="top-center"
  reverseOrder={false}
/>
        {children}
              </div>
      
        </body>
    </html>
    </ClerkProvider>
  );
}
